ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'PAYROLL_EMPLOYEES';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'PAYROLL_INPUT';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'BONUS_INPUT';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'RATES';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'TAX_IMPORT';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'PAYSLIP';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'BONUS_SLIP';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'SES_CUSTOMERS';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'SES_PROJECTS';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'SES_INVOICES';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'SES_PARTNER_COSTS';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'SES_REVENUE';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'SES_MASTERS';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'SES_PROFIT';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'USERS';
ALTER TYPE "PermissionMenu" ADD VALUE IF NOT EXISTS 'PERMISSIONS';

CREATE TABLE "UserPermission" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "menu" "PermissionMenu" NOT NULL,
  "canShow" BOOLEAN NOT NULL DEFAULT true,
  "canView" BOOLEAN NOT NULL DEFAULT true,
  "canEdit" BOOLEAN NOT NULL DEFAULT false,
  "canViewAll" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "UserPermission_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "UserPermission_userId_menu_key" ON "UserPermission"("userId", "menu");
CREATE INDEX "UserPermission_userId_idx" ON "UserPermission"("userId");
CREATE INDEX "UserPermission_menu_idx" ON "UserPermission"("menu");

ALTER TABLE "UserPermission" ADD CONSTRAINT "UserPermission_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "AppUser"("id") ON DELETE CASCADE ON UPDATE CASCADE;
