ALTER TABLE "Payroll" ADD COLUMN "childCareSupportRate" DECIMAL(7,5) NOT NULL DEFAULT 0.00000;
ALTER TABLE "Payroll" ADD COLUMN "childCareSupport" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Payroll" ADD COLUMN "residentTax" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "CompanySetting" ADD COLUMN "childCareSupportRate" DECIMAL(7,5) NOT NULL DEFAULT 0.00000;

ALTER TABLE "FiscalRate" ADD COLUMN "childCareSupportRate" DECIMAL(7,5) NOT NULL DEFAULT 0.00000;
