ALTER TABLE "CompanySetting" ADD COLUMN "payrollPeriodType" TEXT NOT NULL DEFAULT 'PREVIOUS_MONTH';
ALTER TABLE "CompanySetting" ADD COLUMN "payrollPayDay" INTEGER NOT NULL DEFAULT 25;
ALTER TABLE "CompanySetting" ADD COLUMN "payrollClosingDay" INTEGER NOT NULL DEFAULT 31;
ALTER TABLE "CompanySetting" ADD COLUMN "payrollInitialSwitchDay" INTEGER NOT NULL DEFAULT 25;
ALTER TABLE "CompanySetting" ADD COLUMN "payrollLockDay" INTEGER NOT NULL DEFAULT 28;
ALTER TABLE "CompanySetting" ADD COLUMN "payrollLockEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "CompanySetting" ADD COLUMN "payrollForceUpdateEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "CompanySetting" ADD COLUMN "payrollLockTarget" TEXT NOT NULL DEFAULT 'PAYROLL_AND_BONUS';
